---
title: "Untitled"
description: |
  A new article created using the Radix format.
author:
  - name: Nora Jones 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: radix::radix_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



# Theory

* History of CBF: http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3dpsyh%26AN%3d2006-07885-023%26site%3dehost-live
* Overview of computer-based tools and techniques: https://search.proquest.com/docview/2130846961?accountid=14433 
* An Overview of Automated Scoring of Essays: https://search.proquest.com/docview/61858496?accountid=14433
* Übersicht & Beurteilung von Tools mit "Latent semantic analysis (LSA)": https://search.proquest.com/docview/61989560?accountid=14433
* Feedback on micro-features/ micro-features + aggregated scores are superior to only aggregated scores: https://search.proquest.com/docview/2101887422?accountid=14433
* One question is whether these systems offer appropriate or sufficient formative feedback to students about their writing: https://search.proquest.com/docview/2101885496?accountid=14433
* AES nicht so cool: https://search.proquest.com/docview/1322240328?accountid=14433
* Quality of AES ("Agreement rates between automated essay scoring systems and human raters: Meta-analysis"): 
* Toward More Substantively Meaningful Automated Essay Scoring: https://search.proquest.com/docview/61879588?accountid=14433
* Unterschiedliche Strategien, wie SuS Feedback on writing nutzen: https://search.proquest.com/docview/1941339671?accountid=14433
* AES inappropriate for learning: "Automated Evaluation of Texts by Individual Teacher's Model" 2012,  Fujita, Akira; Tamura, Naoyoshi; 


## Forschungsstand

* Formative assessment and writing: A meta-analysis. (2015) Authors: Graham, Steve; Hebert, Michael; Harris, Karen R; 
* Hussein MA, Hassan H, Nassef M. 2019. Automated language essay scoring systems: a literature review. PeerJ Computer Science 5:e208 https://doi.org/10.7717/peerj-cs.208


## Screening

Backward search (3 latest research syntheses):

* https://doi.org/10.1016/j.compedu.2018.12.005
* https://files.eric.ed.gov/fulltext/ED586512.pdf (https://eric.ed.gov/?id=ED586512)
* http://dx.doi.org/10.1016/j.asw.2013.11.007


# Submission

* Educational Research Review https://www.journals.elsevier.com/educational-research-review
* Review of Educational Research https://journals.sagepub.com/home/rer
* Review of Research in Education https://journals.sagepub.com/toc/RRE/current
